version: '3.8'

services:
  api-gateway:
    build: .
    image: ${REGISTRY_USERNAME}/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_DISCOVERY_LOCATOR_ENABLED=true
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_R2DBC_URL=r2dbc:mysql://mysql-db:3306/micro_service_user_db
      - SPRING_R2DBC_USERNAME=root
      - SPRING_R2DBC_PASSWORD=Som1234567
    networks:
      - microservice-network
    restart: always

networks:
  microservice-network:
    driver: bridge

