
# Application Identity
spring.application.name=apigateway
server.port=8080




# Keep this lowercase setting enabled to match standard browser requests
#spring.cloud.gateway.discovery.locator.lower-case-service-name=true



# NEW KEY FOR SPRING BOOT 3.5+: Enable Automatic Routing via Eureka
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true

# Keep this lowercase setting enabled to match standard browser requests
#spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-name=true



#=========================================================================

# Eureka Discovery Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
#========================================================================

# Reactive Database Settings
spring.r2dbc.url=r2dbc:mysql://localhost:3306/micro_service_user_db
spring.r2dbc.username=root
spring.r2dbc.password=Som1234567
spring.r2dbc.pool.initial-size=5
spring.r2dbc.pool.max-size=20

#=====================================================================

# Route Configuration for Order Service
#spring.cloud.gateway.routes[0].id=order-service
#spring.cloud.gateway.routes[0].uri=lb://ORDER-SERVICE
#spring.cloud.gateway.routes[0].predicates[0]=Path=/order-service/**
#spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1
#========================================================================


#=====================================================================

# Route Configuration for Order Service
spring.cloud.gateway.server.webflux.routes[0].id=order-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/order-service/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1
#========================================================================

# Route Configuration for Payment Service
spring.cloud.gateway.server.webflux.routes[1].id=payment-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/payment-service/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=1
#=============================================================================
#========================================================================
# Route Configuration for Product Service
spring.cloud.gateway.server.webflux.routes[2].id=product-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/product-service/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=StripPrefix=1
#=============================================================================








# =====================================================================
# Logging & Log Rotation Configuration
# =====================================================================
logging.file.name=logs/app-error.log
logging.level.root=INFO
logging.level.com.microservice.ecart.apigateway=DEBUG


logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.total-size-cap=1GB
logging.logback.rollingpolicy.max-history=7
